# This is a TOML document.

title = "Simulation configuration"

[general]
quiet = true
mode = "jet"            # jet or survey
multiprocessing = true

[paths]
outpath = "/mnt/nvme1n1/simulations/230423_n50000_s256"

[jet]
training_type = "list"  # gauss or list or clean
num_jet_components = [3, 9]
scaling = "normalize"

[survey]
num_sources = 20
# classes are: jet, gaussian, pointlike
class_distribution = [2, 1, 2]   # average share of each source in the images
scale_sources = true

[image_options]
bundles_train = 500
bundles_valid = 50
bundles_test = 50
bundle_size = 100
img_size = 256
noise = true
noise_level = 15    # maximum intensity of noise in percent
