# This is a TOML document.

title = "Survey simulation configuration"

[general]
quiet = true
mode = "survey"   # jet or survey

[paths]
outpath = "/net/big-tank/POOL/projects/radio/simulations/survey/testing"

[jet]
training_type = "gauss"  # gauss or list or clean
num_jet_components = [3, 6]

[survey]
num_sources = 20
# classes are: jet, gaussian, ponitlike
class_distribution = [2, 1, 2]   # average share of each source in the images
scale_sources = true

[image_options]
bundles_train = 1
bundles_valid = 1
bundles_test = 1
bundle_size = 10
img_size = 1024
noise = false
noise_level = 15    # maximum intensity of noise in percent
